name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: blang/latex
    steps:
      - uses: actions/checkout@v2
      - name: Build pdf
        run: |
          latexmk -pdf main.tex
          ls
