name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: blang/latex
    steps:
      - uses: actions/checkout@v2
      - name: Build pdf
        run: |
          latexmk -pdf main.tex
          mkdir build
          mv main.pdf build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true